### ISSUE TITLE
migrate settings to .env from docker-compose

### ISSUE THREAD

**Issue by johan-rocha** [Project-GrADyS/ardupilot_ros_sitl_docker#14]
## Description
.env becomes more suitable for variables shared between services

## Tasks
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa, dívida tarefas grandes e complexas em tarefas simples.
- [x] create .env
- [x] add necessary environment variables to each service in docker-compose and assign the .env variables
- [x] add the SIM_MODE variable to define whether the script will run on the simulator or serial interface
- [x] adapt entrypoint script to support environment variables

## Tests / Rating
Especifique os critérios de teste ou avaliação que serão usados para garantir que a solução seja eficaz. 
- [ ] unit test at each entrypoint

## Assigned
@johan-rocha
