### ISSUE TITLE
Add serial interface support

### ISSUE THREAD

**Issue by johan-rocha** [Project-GrADyS/ardupilot_ros_sitl_docker#15]
## Description
Docker support to recognize FCU serial input, required for MAVROS and DDS connection

## Tasks
- [x] add device to docker compose
- [x] adapt ros entrypoint to support serial connection
- [x] document permissions scheme and folder location

## Tests / Rating
- [x] hardware test

## Assigned
@johan-rocha ]
