### ISSUE TITLE
Create a vehicle service command class

### ISSUE THREAD

**Issue by johan-rocha** [Project-GrADyS/ardupilot_ros_sitl_docker#2]
## Description
This Issue focuses on defining a class that can instantiate Ardupilot vehicles and assign commands to them.

## Tasks
- [x] Define and list essential methods
- [x] Check ROS services and their respective message structures
- [ ] The class must allow the use of many vehicles
- [ ] Make programs that use the service class

## Tests / Rating
- [ ] Check the MAVROS topics to see if each service is running correctly 

## Assigned
@johan-rocha
