### ISSUE TITLE
setArm must make attempts to arm until it succeeds.

### ISSUE THREAD

**Issue by johan-rocha** [Project-GrADyS/ardupilot_ros_sitl_docker#3]
## Description
The setArm() method should attempt to arm the vehicle until successful, so that it does not require user interaction with the ROS directly.

## Tasks
- [x] If possible, monitor the state of the vehicle to arm only when the "ready to arm" condition is satisfied
- [x] If the first task is not possible, try to arm until you can
- [x] improve encapsulation in the method

## Tests / Rating 
- [x] The node must be able to run automatically on docker compose up
